import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const theme = cookies().get('theme')

  return (
    <html lang="pt-BR" className={theme?.value}>
      <body
        className={`${inter.className} bg-slate-100 text-gray-950 dark:bg-gray-950 dark:text-zinc-100`}
      >
        {children}
      </body>
    </html>
  )
}
